import Link from 'next/link';

export function Header(){return <header className="nav-shell"><div className="container h-[76px] flex items-center justify-between"><Link href="/" className="block"><div className="font-bold tracking-tight">SATYVEER SINGH</div><div className="mono text-[9px] muted mt-1 tracking-wider">AI SOLUTION ENGINEERING · GENAI · AGENTIC AI</div></Link><div className="hidden md:flex items-center gap-7 text-sm muted"><Link className="nav-link" href="/#solutions">Solutions</Link><Link className="nav-link" href="/#architecture">Architecture</Link><Link className="nav-link" href="/#journey">Journey</Link><Link className="nav-link" href="/#about">About</Link><Link className="nav-link" href="/#contact">Contact</Link></div><a className="btn btn-secondary text-sm" href="mailto:satyveersingh2612@gmail.com">Let's Connect</a></div></header>}

export function FlowNode({label,active=false,small=false}:{label:string,active?:boolean,small?:boolean}){return <div className={`flow-node ${active?'active':''} ${small?'text-xs':''}`}><span className="flow-dot"/>{label}</div>}

export function CaseHero({eyebrow,title,subtitle,metric,tags}:{eyebrow:string,title:string,subtitle:string,metric?:string,tags:string[]}){return <section className="gridbg"><div className="container section pb-20"><Link href="/#solutions" className="mono text-xs muted">← Back to solutions</Link><div className="eyebrow mt-12">{eyebrow}</div><div className="grid lg:grid-cols-[1fr_310px] gap-12 items-end mt-4"><div><h1 className="title max-w-4xl">{title}</h1><p className="text-xl md:text-2xl leading-9 muted max-w-3xl mt-7">{subtitle}</p><div className="flex flex-wrap gap-2 mt-7">{tags.map(t=><span className="pill" key={t}>{t}</span>)}</div></div>{metric&&<div className="card glow p-6"><div className="mono text-xs muted">OUTCOME / SIGNAL</div><div className="metric font-semibold mt-4">{metric}</div></div>}</div></div></section>}

export function CaseSection({number,title,children}:{number:string,title:string,children:React.ReactNode}){return <section className="section border-t line"><div className="container grid md:grid-cols-[180px_1fr] gap-8"><div className="mono text-xs accent">{number}</div><div className="case-copy"><h2 className="h2">{title}</h2><div className="muted leading-8 mt-6">{children}</div></div></div></section>}

export function ArchitectureFlow({steps}:{steps:string[]}){return <div className="card p-6 md:p-7 smallgrid"><div className="space-y-2">{steps.map((s,i)=><div key={s}><div className={`flow-node ${i===steps.length-1?'active':''} text-sm`}>{s}</div>{i<steps.length-1&&<div className="text-center muted text-xs py-2">↓</div>}</div>)}</div></div>}

export function ScreenshotShowcase({src,alt,caption}:{src:string,alt:string,caption?:string}){return <div className="card overflow-hidden border border-slate-800/80 bg-slate-900/60 p-2 md:p-3 my-8 group transition-all duration-300 hover:border-slate-700"><div className="relative overflow-hidden rounded-xl bg-slate-950 border border-slate-800/80"><div className="flex items-center justify-between px-4 py-2.5 bg-slate-900/90 border-b border-slate-800/80 text-xs"><div className="flex items-center gap-1.5"><span className="w-2.5 h-2.5 rounded-full bg-red-500/70 inline-block"/><span className="w-2.5 h-2.5 rounded-full bg-yellow-500/70 inline-block"/><span className="w-2.5 h-2.5 rounded-full bg-green-500/70 inline-block"/></div><div className="mono text-[11px] text-slate-400 truncate max-w-[280px] sm:max-w-md">{caption||alt}</div><div className="mono text-[10px] text-blue-400 font-semibold px-2 py-0.5 rounded bg-blue-500/10 border border-blue-500/20">PRODUCTION UI</div></div><img src={src} alt={alt} className="w-full h-auto object-cover rounded-b-xl transition-transform duration-500 group-hover:scale-[1.01]"/></div>{caption&&<div className="mono text-xs text-slate-400 text-center mt-3 mb-1 px-2">{caption}</div>}</div>}

export function Footer(){return <footer className="container py-9 border-t line flex flex-col md:flex-row justify-between gap-3 text-sm muted"><div><strong className="text-white">SATYVEER SINGH</strong><div className="mono text-xs mt-1">AI/ML ENGINEER · GENAI · AGENTIC AI</div></div><div>© 2026 Satyveer Singh · Enterprise AI & Automation Solutions</div></footer>}
